name: EndlessSkills
version: '${project.version}'
main: com.airijko.endlessskills.EndlessSkills
depend: [EndlessCore]
api-version: '1.20'
commands:
  endless:
    description: Main command for EndlessSkills plugin.
    usage: /<command> [reload|skills|resetattributes|level]
  reload:
    description: Reloads the plugin.
    usage: /<command>
  skills:
    description: Opens the skills GUI.
    usage: /<command>
  resetattributes:
    description: Resets the attributes.
    usage: /<command>
  level:
    description: Manages levels.
    usage: /<command>
  resetskillpoints:
    description: Resets the skill points.
    usage: /<command>
