name: EndlessSkills
version: '${project.version}'
main: me.airijko.endlessskills.EndlessSkills
api-version: '1.20'
commands:
  endless:
    description: Reloads the EndlessSkills plugin
    usage: /<command> reload