name: EndlessSkills
version: '1.0'
main: me.airijko.endlessskills.EndlessSkills
api-version: '1.20'
commands:
  endless:
    description: Reloads the EndlessSkills plugin or opens the Endless Skills GUI
    usage: /<command> [reload|skills]
